### ISSUE TITLE
Node dependencies in tests

### ISSUE THREAD

**Issue by xZarisx** [tuxsudo/react-starter#25] opened 2016-08-23 17:34 UTC
running the test for a component that depended on react-lazy-component gave this error:

search-alpha/src/app/components/Image/node_modules/react-lazy-component/src/Component.js:1
(function (exports, require, module, __filename, __dirname) { import { Component, PropTypes } from 'react';
                                                             ^^^^^^
SyntaxError: Unexpected token import

**Comment by tuxsudo** [comment] 2017-02-03 14:30
this is a duplicate of #34

**Closed as completed by tuxsudo** 2017-02-03 14:30 UTC
Labels: duplicate
